In [1]:
%matplotlib inline
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
# http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html
iris = datasets.load_iris()
list(iris.keys())

['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename']

In [28]:
# First calculating the properility for the sepal length
x_sl = iris["data"][:, 0:1] 
y_sl = (iris["target"] == 2).astype(np.int)  # array of 1 if Iris-Virginica, else 0
# Create and train the regression model
log_reg_sl = LogisticRegression()
log_reg_sl.fit(x_sl, y_sl)
# Get predicition
print("Properility: First value No, second value Yes:")
print(log_reg_sl.predict_proba([[4.8]]))
print("Is Iris-Virginica (0 = false, 1 = true):")
print(log_reg_sl.predict([[4.8]]))

Properility: First value No, second value Yes:
[[0.96762366 0.03237634]]
Is Iris-Virginica (0 = false, 1 = true):
[0]


In [33]:
# Now calculating the properility for the sepal width
x_sw = iris["data"][:, 1:2] 
y_sw = (iris["target"] == 2).astype(np.int) 
# Create and train the regression model
log_reg_sw = LogisticRegression()
log_reg_sw.fit(x_sw, y_sw)
# Get predicition
print("Properility: First value No, second value Yes:")
print(log_reg_sw.predict_proba([[2.5]]))
print("Is Iris-Virginica (0 = false, 1 = true):")
print(log_reg_sw.predict([[2.5]]))

Properility: First value No, second value Yes:
[[0.5933503 0.4066497]]
Is Iris-Virginica (0 = false, 1 = true):
[0]


In [34]:
# Now calculating the properility for the pedal length
x_pl = iris["data"][:, 2:3] 
y_pl = (iris["target"] == 2).astype(np.int) 
# Create and train the regression model
log_reg_pl = LogisticRegression()
log_reg_pl.fit(x_pl, y_pl)
# Get predicition
print("Properility: First value No, second value Yes:")
print(log_reg_pl.predict_proba([[5.3]]))
print("Is Iris-Virginica (0 = false, 1 = true):")
print(log_reg_pl.predict([[5.3]]))

Properility: First value No, second value Yes:
[[0.17910091 0.82089909]]
Is Iris-Virginica (0 = false, 1 = true):
[1]


In [38]:
# Last calculating the properility for the pedal width
x_pw = iris["data"][:, 3:] 
y_pw = (iris["target"] == 2).astype(np.int) 
# Create and train the regression model
log_reg_pw = LogisticRegression()
log_reg_pw.fit(x_pw, y_pw)
# Get predicition
print("Properility: First value No, second value Yes:")
print(log_reg_pw.predict_proba([[2.4]]))
print("Is Iris-Virginica (0 = false, 1 = true):")
print(log_reg_pw.predict([[2.4]]))

Properility: First value No, second value Yes:
[[0.03898943 0.96101057]]
Is Iris-Virginica (0 = false, 1 = true):
[1]


In [39]:
# calculating the properility with all values
x = iris["data"][:, :] 
y = (iris["target"] == 2).astype(np.int) 
# Create and train the regression model
log_reg = LogisticRegression()
log_reg.fit(x, y)
# Get predicition
print("Properility: First value No, second value Yes:")
print(log_reg.predict_proba([[4.8,2.5,5.3,2.4]]))
print("Is Iris-Virginica (0 = false, 1 = true):")
print(log_reg.predict([[4.8,2.5,5.3,2.4]]))

Properility: First value No, second value Yes:
[[0.023505 0.976495]]
Is Iris-Virginica (0 = false, 1 = true):
[1]
