In [1]:
import numpy as np
print(np.__version__)

1.18.1


In [9]:
array = np.arange(9)
print(array)

[0 1 2 3 4 5 6 7 8]


In [10]:
bool_matirx = np.full((3, 3), True, dtype=bool)
print(bool_matirx)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [15]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array[array % 2 == 1])
array[array % 2 == 1] = -1
print(array)

[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [16]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [17]:
array = np.arange(10)
array_two = array.reshape(2, -1)
print(array_two)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
stack = np.vstack([a, b])
print(stack)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
stack = np.hstack([a, b])
print(stack)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [21]:
a = np.array([1,2,3])
a2 = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(a2)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [23]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a == b))

(array([1, 3, 5, 7], dtype=int64),)


In [26]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a >= 5) & (a <= 10)])

[ 6  9 10]


In [27]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [28]:
arr = np.arange(9).reshape(3,3)
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [29]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [30]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [31]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [33]:
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[9.05501321, 7.86705085, 7.33342384],
       [8.4954193 , 9.71264902, 7.52645422],
       [8.37877857, 7.26758952, 5.21479467],
       [9.2479203 , 8.34170721, 5.2818106 ],
       [6.05188842, 8.83938882, 8.35008739]])

In [39]:
rand_arr = np.random.random([5,3])
np.set_printoptions(precision=3)
rand_arr

array([[0.513, 0.322, 0.059],
       [0.76 , 0.244, 0.288],
       [0.445, 0.242, 0.309],
       [0.059, 0.304, 0.869],
       [0.588, 0.789, 0.768]])

In [43]:
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000575, 0.000891, 0.000209],
       [0.000185, 0.000108, 0.00022 ],
       [0.000979, 0.000812, 0.000172]])

In [44]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [67]:
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=1000)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [68]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)